{{ if .Values.collector_proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.collector_proxy.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.name }}"
    app.kubernetes.io/managed-by: helm
  {{- with .Values.collector_proxy.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.collector_proxy.service.type }}
  selector:
    app: enterprise-collector-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.collector_proxy.service.port }}
      targetPort: 8080
{{ end }}
